// Code generated by internal/_generate/compileroptions; DO NOT EDIT.

package core

import (
	"slices"

	"github.com/microsoft/TypeScript/tsc/internal/collections"
)

func (options *CompilerOptions) Clone() *CompilerOptions {
	target := &CompilerOptions{}
	target.AllowJs = options.AllowJs
	target.AllowArbitraryExtensions = options.AllowArbitraryExtensions
	target.AllowImportingTsExtensions = options.AllowImportingTsExtensions
	target.AllowNonTsExtensions = options.AllowNonTsExtensions
	target.AllowUmdGlobalAccess = options.AllowUmdGlobalAccess
	target.AllowUnreachableCode = options.AllowUnreachableCode
	target.AllowUnusedLabels = options.AllowUnusedLabels
	target.AssumeChangesOnlyAffectDirectDependencies = options.AssumeChangesOnlyAffectDirectDependencies
	target.CheckJs = options.CheckJs
	target.CustomConditions = options.CustomConditions
	target.Composite = options.Composite
	target.EmitDeclarationOnly = options.EmitDeclarationOnly
	target.EmitBOM = options.EmitBOM
	target.EmitDecoratorMetadata = options.EmitDecoratorMetadata
	target.Declaration = options.Declaration
	target.DeclarationDir = options.DeclarationDir
	target.DeclarationMap = options.DeclarationMap
	target.DeduplicatePackages = options.DeduplicatePackages
	target.DisableSizeLimit = options.DisableSizeLimit
	target.DisableSourceOfProjectReferenceRedirect = options.DisableSourceOfProjectReferenceRedirect
	target.DisableSolutionSearching = options.DisableSolutionSearching
	target.DisableReferencedProjectLoad = options.DisableReferencedProjectLoad
	target.ErasableSyntaxOnly = options.ErasableSyntaxOnly
	target.ExactOptionalPropertyTypes = options.ExactOptionalPropertyTypes
	target.ExperimentalDecorators = options.ExperimentalDecorators
	target.ForceConsistentCasingInFileNames = options.ForceConsistentCasingInFileNames
	target.IsolatedModules = options.IsolatedModules
	target.IsolatedDeclarations = options.IsolatedDeclarations
	target.IgnoreConfig = options.IgnoreConfig
	target.IgnoreDeprecations = options.IgnoreDeprecations
	target.ImportHelpers = options.ImportHelpers
	target.InlineSourceMap = options.InlineSourceMap
	target.InlineSources = options.InlineSources
	target.Init = options.Init
	target.Incremental = options.Incremental
	target.Jsx = options.Jsx
	target.JsxFactory = options.JsxFactory
	target.JsxFragmentFactory = options.JsxFragmentFactory
	target.JsxImportSource = options.JsxImportSource
	target.Lib = options.Lib
	target.LibReplacement = options.LibReplacement
	target.Locale = options.Locale
	target.MapRoot = options.MapRoot
	target.Module = options.Module
	target.ModuleResolution = options.ModuleResolution
	target.ModuleSuffixes = options.ModuleSuffixes
	target.ModuleDetection = options.ModuleDetection
	target.NewLine = options.NewLine
	target.NoEmit = options.NoEmit
	target.NoCheck = options.NoCheck
	target.NoErrorTruncation = options.NoErrorTruncation
	target.NoFallthroughCasesInSwitch = options.NoFallthroughCasesInSwitch
	target.NoImplicitAny = options.NoImplicitAny
	target.NoImplicitThis = options.NoImplicitThis
	target.NoImplicitReturns = options.NoImplicitReturns
	target.NoEmitHelpers = options.NoEmitHelpers
	target.NoLib = options.NoLib
	target.NoPropertyAccessFromIndexSignature = options.NoPropertyAccessFromIndexSignature
	target.NoUncheckedIndexedAccess = options.NoUncheckedIndexedAccess
	target.NoEmitOnError = options.NoEmitOnError
	target.NoUnusedLocals = options.NoUnusedLocals
	target.NoUnusedParameters = options.NoUnusedParameters
	target.NoResolve = options.NoResolve
	target.NoImplicitOverride = options.NoImplicitOverride
	target.NoUncheckedSideEffectImports = options.NoUncheckedSideEffectImports
	target.OutDir = options.OutDir
	target.Paths = options.Paths
	target.PreserveConstEnums = options.PreserveConstEnums
	target.PreserveSymlinks = options.PreserveSymlinks
	target.Project = options.Project
	target.ResolveJsonModule = options.ResolveJsonModule
	target.ResolvePackageJsonExports = options.ResolvePackageJsonExports
	target.ResolvePackageJsonImports = options.ResolvePackageJsonImports
	target.RemoveComments = options.RemoveComments
	target.RewriteRelativeImportExtensions = options.RewriteRelativeImportExtensions
	target.ReactNamespace = options.ReactNamespace
	target.RootDir = options.RootDir
	target.RootDirs = options.RootDirs
	target.SkipLibCheck = options.SkipLibCheck
	target.StableTypeOrdering = options.StableTypeOrdering
	target.Strict = options.Strict
	target.StrictBindCallApply = options.StrictBindCallApply
	target.StrictBuiltinIteratorReturn = options.StrictBuiltinIteratorReturn
	target.StrictFunctionTypes = options.StrictFunctionTypes
	target.StrictNullChecks = options.StrictNullChecks
	target.StrictPropertyInitialization = options.StrictPropertyInitialization
	target.StripInternal = options.StripInternal
	target.SkipDefaultLibCheck = options.SkipDefaultLibCheck
	target.SourceMap = options.SourceMap
	target.SourceRoot = options.SourceRoot
	target.SuppressOutputPathCheck = options.SuppressOutputPathCheck
	target.Target = options.Target
	target.TraceResolution = options.TraceResolution
	target.TsBuildInfoFile = options.TsBuildInfoFile
	target.TypeRoots = options.TypeRoots
	target.Types = options.Types
	target.UseDefineForClassFields = options.UseDefineForClassFields
	target.UseUnknownInCatchVariables = options.UseUnknownInCatchVariables
	target.VerbatimModuleSyntax = options.VerbatimModuleSyntax
	target.MaxNodeModuleJsDepth = options.MaxNodeModuleJsDepth
	target.AllowSyntheticDefaultImports = options.AllowSyntheticDefaultImports
	target.AlwaysStrict = options.AlwaysStrict
	target.BaseUrl = options.BaseUrl
	target.DownlevelIteration = options.DownlevelIteration
	target.ESModuleInterop = options.ESModuleInterop
	target.OutFile = options.OutFile
	target.ConfigFilePath = options.ConfigFilePath
	target.NoDtsResolution = options.NoDtsResolution
	target.PathsBasePath = options.PathsBasePath
	target.Diagnostics = options.Diagnostics
	target.ExtendedDiagnostics = options.ExtendedDiagnostics
	target.GenerateCpuProfile = options.GenerateCpuProfile
	target.GenerateTrace = options.GenerateTrace
	target.ListEmittedFiles = options.ListEmittedFiles
	target.ListFiles = options.ListFiles
	target.ExplainFiles = options.ExplainFiles
	target.ListFilesOnly = options.ListFilesOnly
	target.NoEmitForJsFiles = options.NoEmitForJsFiles
	target.PreserveWatchOutput = options.PreserveWatchOutput
	target.Pretty = options.Pretty
	target.Version = options.Version
	target.Watch = options.Watch
	target.ShowConfig = options.ShowConfig
	target.Build = options.Build
	target.Help = options.Help
	target.All = options.All
	target.RunExternalCode = options.RunExternalCode
	target.PprofDir = options.PprofDir
	target.SingleThreaded = options.SingleThreaded
	target.Quiet = options.Quiet
	target.Checkers = options.Checkers
	return target
}

func (options *CompilerOptions) Equals(other *CompilerOptions) bool {
	if options == other {
		return true
	}
	if options == nil || other == nil {
		return false
	}
	if options.AllowJs != other.AllowJs {
		return false
	}
	if options.AllowArbitraryExtensions != other.AllowArbitraryExtensions {
		return false
	}
	if options.AllowImportingTsExtensions != other.AllowImportingTsExtensions {
		return false
	}
	if options.AllowNonTsExtensions != other.AllowNonTsExtensions {
		return false
	}
	if options.AllowUmdGlobalAccess != other.AllowUmdGlobalAccess {
		return false
	}
	if options.AllowUnreachableCode != other.AllowUnreachableCode {
		return false
	}
	if options.AllowUnusedLabels != other.AllowUnusedLabels {
		return false
	}
	if options.AssumeChangesOnlyAffectDirectDependencies != other.AssumeChangesOnlyAffectDirectDependencies {
		return false
	}
	if options.CheckJs != other.CheckJs {
		return false
	}
	if !slices.Equal(options.CustomConditions, other.CustomConditions) {
		return false
	}
	if options.Composite != other.Composite {
		return false
	}
	if options.EmitDeclarationOnly != other.EmitDeclarationOnly {
		return false
	}
	if options.EmitBOM != other.EmitBOM {
		return false
	}
	if options.EmitDecoratorMetadata != other.EmitDecoratorMetadata {
		return false
	}
	if options.Declaration != other.Declaration {
		return false
	}
	if options.DeclarationDir != other.DeclarationDir {
		return false
	}
	if options.DeclarationMap != other.DeclarationMap {
		return false
	}
	if options.DeduplicatePackages != other.DeduplicatePackages {
		return false
	}
	if options.DisableSizeLimit != other.DisableSizeLimit {
		return false
	}
	if options.DisableSourceOfProjectReferenceRedirect != other.DisableSourceOfProjectReferenceRedirect {
		return false
	}
	if options.DisableSolutionSearching != other.DisableSolutionSearching {
		return false
	}
	if options.DisableReferencedProjectLoad != other.DisableReferencedProjectLoad {
		return false
	}
	if options.ErasableSyntaxOnly != other.ErasableSyntaxOnly {
		return false
	}
	if options.ExactOptionalPropertyTypes != other.ExactOptionalPropertyTypes {
		return false
	}
	if options.ExperimentalDecorators != other.ExperimentalDecorators {
		return false
	}
	if options.ForceConsistentCasingInFileNames != other.ForceConsistentCasingInFileNames {
		return false
	}
	if options.IsolatedModules != other.IsolatedModules {
		return false
	}
	if options.IsolatedDeclarations != other.IsolatedDeclarations {
		return false
	}
	if options.IgnoreConfig != other.IgnoreConfig {
		return false
	}
	if options.IgnoreDeprecations != other.IgnoreDeprecations {
		return false
	}
	if options.ImportHelpers != other.ImportHelpers {
		return false
	}
	if options.InlineSourceMap != other.InlineSourceMap {
		return false
	}
	if options.InlineSources != other.InlineSources {
		return false
	}
	if options.Init != other.Init {
		return false
	}
	if options.Incremental != other.Incremental {
		return false
	}
	if options.Jsx != other.Jsx {
		return false
	}
	if options.JsxFactory != other.JsxFactory {
		return false
	}
	if options.JsxFragmentFactory != other.JsxFragmentFactory {
		return false
	}
	if options.JsxImportSource != other.JsxImportSource {
		return false
	}
	if !slices.Equal(options.Lib, other.Lib) {
		return false
	}
	if options.LibReplacement != other.LibReplacement {
		return false
	}
	if options.Locale != other.Locale {
		return false
	}
	if options.MapRoot != other.MapRoot {
		return false
	}
	if options.Module != other.Module {
		return false
	}
	if options.ModuleResolution != other.ModuleResolution {
		return false
	}
	if !slices.Equal(options.ModuleSuffixes, other.ModuleSuffixes) {
		return false
	}
	if options.ModuleDetection != other.ModuleDetection {
		return false
	}
	if options.NewLine != other.NewLine {
		return false
	}
	if options.NoEmit != other.NoEmit {
		return false
	}
	if options.NoCheck != other.NoCheck {
		return false
	}
	if options.NoErrorTruncation != other.NoErrorTruncation {
		return false
	}
	if options.NoFallthroughCasesInSwitch != other.NoFallthroughCasesInSwitch {
		return false
	}
	if options.NoImplicitAny != other.NoImplicitAny {
		return false
	}
	if options.NoImplicitThis != other.NoImplicitThis {
		return false
	}
	if options.NoImplicitReturns != other.NoImplicitReturns {
		return false
	}
	if options.NoEmitHelpers != other.NoEmitHelpers {
		return false
	}
	if options.NoLib != other.NoLib {
		return false
	}
	if options.NoPropertyAccessFromIndexSignature != other.NoPropertyAccessFromIndexSignature {
		return false
	}
	if options.NoUncheckedIndexedAccess != other.NoUncheckedIndexedAccess {
		return false
	}
	if options.NoEmitOnError != other.NoEmitOnError {
		return false
	}
	if options.NoUnusedLocals != other.NoUnusedLocals {
		return false
	}
	if options.NoUnusedParameters != other.NoUnusedParameters {
		return false
	}
	if options.NoResolve != other.NoResolve {
		return false
	}
	if options.NoImplicitOverride != other.NoImplicitOverride {
		return false
	}
	if options.NoUncheckedSideEffectImports != other.NoUncheckedSideEffectImports {
		return false
	}
	if options.OutDir != other.OutDir {
		return false
	}
	if !compilerOptionsStringListMapEqual(options.Paths, other.Paths) {
		return false
	}
	if options.PreserveConstEnums != other.PreserveConstEnums {
		return false
	}
	if options.PreserveSymlinks != other.PreserveSymlinks {
		return false
	}
	if options.Project != other.Project {
		return false
	}
	if options.ResolveJsonModule != other.ResolveJsonModule {
		return false
	}
	if options.ResolvePackageJsonExports != other.ResolvePackageJsonExports {
		return false
	}
	if options.ResolvePackageJsonImports != other.ResolvePackageJsonImports {
		return false
	}
	if options.RemoveComments != other.RemoveComments {
		return false
	}
	if options.RewriteRelativeImportExtensions != other.RewriteRelativeImportExtensions {
		return false
	}
	if options.ReactNamespace != other.ReactNamespace {
		return false
	}
	if options.RootDir != other.RootDir {
		return false
	}
	if !slices.Equal(options.RootDirs, other.RootDirs) {
		return false
	}
	if options.SkipLibCheck != other.SkipLibCheck {
		return false
	}
	if options.StableTypeOrdering != other.StableTypeOrdering {
		return false
	}
	if options.Strict != other.Strict {
		return false
	}
	if options.StrictBindCallApply != other.StrictBindCallApply {
		return false
	}
	if options.StrictBuiltinIteratorReturn != other.StrictBuiltinIteratorReturn {
		return false
	}
	if options.StrictFunctionTypes != other.StrictFunctionTypes {
		return false
	}
	if options.StrictNullChecks != other.StrictNullChecks {
		return false
	}
	if options.StrictPropertyInitialization != other.StrictPropertyInitialization {
		return false
	}
	if options.StripInternal != other.StripInternal {
		return false
	}
	if options.SkipDefaultLibCheck != other.SkipDefaultLibCheck {
		return false
	}
	if options.SourceMap != other.SourceMap {
		return false
	}
	if options.SourceRoot != other.SourceRoot {
		return false
	}
	if options.SuppressOutputPathCheck != other.SuppressOutputPathCheck {
		return false
	}
	if options.Target != other.Target {
		return false
	}
	if options.TraceResolution != other.TraceResolution {
		return false
	}
	if options.TsBuildInfoFile != other.TsBuildInfoFile {
		return false
	}
	if !slices.Equal(options.TypeRoots, other.TypeRoots) {
		return false
	}
	if !slices.Equal(options.Types, other.Types) {
		return false
	}
	if options.UseDefineForClassFields != other.UseDefineForClassFields {
		return false
	}
	if options.UseUnknownInCatchVariables != other.UseUnknownInCatchVariables {
		return false
	}
	if options.VerbatimModuleSyntax != other.VerbatimModuleSyntax {
		return false
	}
	if !intPointersEqual(options.MaxNodeModuleJsDepth, other.MaxNodeModuleJsDepth) {
		return false
	}
	if options.AllowSyntheticDefaultImports != other.AllowSyntheticDefaultImports {
		return false
	}
	if options.AlwaysStrict != other.AlwaysStrict {
		return false
	}
	if options.BaseUrl != other.BaseUrl {
		return false
	}
	if options.DownlevelIteration != other.DownlevelIteration {
		return false
	}
	if options.ESModuleInterop != other.ESModuleInterop {
		return false
	}
	if options.OutFile != other.OutFile {
		return false
	}
	if options.ConfigFilePath != other.ConfigFilePath {
		return false
	}
	if options.NoDtsResolution != other.NoDtsResolution {
		return false
	}
	if options.PathsBasePath != other.PathsBasePath {
		return false
	}
	if options.Diagnostics != other.Diagnostics {
		return false
	}
	if options.ExtendedDiagnostics != other.ExtendedDiagnostics {
		return false
	}
	if options.GenerateCpuProfile != other.GenerateCpuProfile {
		return false
	}
	if options.GenerateTrace != other.GenerateTrace {
		return false
	}
	if options.ListEmittedFiles != other.ListEmittedFiles {
		return false
	}
	if options.ListFiles != other.ListFiles {
		return false
	}
	if options.ExplainFiles != other.ExplainFiles {
		return false
	}
	if options.ListFilesOnly != other.ListFilesOnly {
		return false
	}
	if options.NoEmitForJsFiles != other.NoEmitForJsFiles {
		return false
	}
	if options.PreserveWatchOutput != other.PreserveWatchOutput {
		return false
	}
	if options.Pretty != other.Pretty {
		return false
	}
	if options.Version != other.Version {
		return false
	}
	if options.Watch != other.Watch {
		return false
	}
	if options.ShowConfig != other.ShowConfig {
		return false
	}
	if options.Build != other.Build {
		return false
	}
	if options.Help != other.Help {
		return false
	}
	if options.All != other.All {
		return false
	}
	if options.RunExternalCode != other.RunExternalCode {
		return false
	}
	if options.PprofDir != other.PprofDir {
		return false
	}
	if options.SingleThreaded != other.SingleThreaded {
		return false
	}
	if options.Quiet != other.Quiet {
		return false
	}
	if !intPointersEqual(options.Checkers, other.Checkers) {
		return false
	}
	return true
}

func intPointersEqual(left *int, right *int) bool {
	if left == right {
		return true
	}
	if left == nil || right == nil {
		return false
	}
	return *left == *right
}

func compilerOptionsStringListMapEqual(left *collections.OrderedMap[string, []string], right *collections.OrderedMap[string, []string]) bool {
	if left == right {
		return true
	}
	if left == nil || right == nil || left.Size() != right.Size() {
		return false
	}
	for key, leftValue := range left.Entries() {
		rightValue, ok := right.Get(key)
		if !ok || !slices.Equal(leftValue, rightValue) {
			return false
		}
	}
	return true
}
