// Code generated by internal/_generate/userpreferences; DO NOT EDIT.

package lsutil

import (
	"strings"

	"github.com/microsoft/TypeScript/tsc/internal/core"
	"github.com/microsoft/TypeScript/tsc/internal/modulespecifiers"
)

func generatedUserPreferenceFieldInfos() []fieldInfo {
	return []fieldInfo{
		{rawName: "baseIndentSize", configPath: "format.baseIndentSize", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.EditorSettings.BaseIndentSize = parsePreferenceInt(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceInt(int(p.FormatCodeSettings.EditorSettings.BaseIndentSize))
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.EditorSettings.BaseIndentSize != 0 {
				p.FormatCodeSettings.EditorSettings.BaseIndentSize = overrides.FormatCodeSettings.EditorSettings.BaseIndentSize
			}
		}},
		{rawName: "indentSize", configPath: "format.indentSize", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.EditorSettings.IndentSize = parsePreferenceInt(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceInt(int(p.FormatCodeSettings.EditorSettings.IndentSize))
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.EditorSettings.IndentSize != 0 {
				p.FormatCodeSettings.EditorSettings.IndentSize = overrides.FormatCodeSettings.EditorSettings.IndentSize
			}
		}},
		{rawName: "tabSize", configPath: "format.tabSize", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.EditorSettings.TabSize = parsePreferenceInt(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceInt(int(p.FormatCodeSettings.EditorSettings.TabSize))
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.EditorSettings.TabSize != 0 {
				p.FormatCodeSettings.EditorSettings.TabSize = overrides.FormatCodeSettings.EditorSettings.TabSize
			}
		}},
		{rawName: "newLineCharacter", configPath: "format.newLineCharacter", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.EditorSettings.NewLineCharacter = parsePreferenceString(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceString(string(p.FormatCodeSettings.EditorSettings.NewLineCharacter))
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if string(overrides.FormatCodeSettings.EditorSettings.NewLineCharacter) != "" {
				p.FormatCodeSettings.EditorSettings.NewLineCharacter = overrides.FormatCodeSettings.EditorSettings.NewLineCharacter
			}
		}},
		{rawName: "convertTabsToSpaces", configPath: "format.convertTabsToSpaces", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.EditorSettings.ConvertTabsToSpaces = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.EditorSettings.ConvertTabsToSpaces)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.EditorSettings.ConvertTabsToSpaces != core.TSUnknown {
				p.FormatCodeSettings.EditorSettings.ConvertTabsToSpaces = overrides.FormatCodeSettings.EditorSettings.ConvertTabsToSpaces
			}
		}},
		{rawName: "indentStyle", configPath: "format.indentStyle", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.EditorSettings.IndentStyle = parseIndentStyle(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceInt(int(p.FormatCodeSettings.EditorSettings.IndentStyle))
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.EditorSettings.IndentStyle != 0 {
				p.FormatCodeSettings.EditorSettings.IndentStyle = overrides.FormatCodeSettings.EditorSettings.IndentStyle
			}
		}},
		{rawName: "trimTrailingWhitespace", configPath: "format.trimTrailingWhitespace", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.EditorSettings.TrimTrailingWhitespace = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.EditorSettings.TrimTrailingWhitespace)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.EditorSettings.TrimTrailingWhitespace != core.TSUnknown {
				p.FormatCodeSettings.EditorSettings.TrimTrailingWhitespace = overrides.FormatCodeSettings.EditorSettings.TrimTrailingWhitespace
			}
		}},
		{rawName: "insertSpaceAfterCommaDelimiter", configPath: "format.insertSpaceAfterCommaDelimiter", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.InsertSpaceAfterCommaDelimiter = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.InsertSpaceAfterCommaDelimiter)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.InsertSpaceAfterCommaDelimiter != core.TSUnknown {
				p.FormatCodeSettings.InsertSpaceAfterCommaDelimiter = overrides.FormatCodeSettings.InsertSpaceAfterCommaDelimiter
			}
		}},
		{rawName: "insertSpaceAfterSemicolonInForStatements", configPath: "format.insertSpaceAfterSemicolonInForStatements", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.InsertSpaceAfterSemicolonInForStatements = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.InsertSpaceAfterSemicolonInForStatements)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.InsertSpaceAfterSemicolonInForStatements != core.TSUnknown {
				p.FormatCodeSettings.InsertSpaceAfterSemicolonInForStatements = overrides.FormatCodeSettings.InsertSpaceAfterSemicolonInForStatements
			}
		}},
		{rawName: "insertSpaceBeforeAndAfterBinaryOperators", configPath: "format.insertSpaceBeforeAndAfterBinaryOperators", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.InsertSpaceBeforeAndAfterBinaryOperators = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.InsertSpaceBeforeAndAfterBinaryOperators)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.InsertSpaceBeforeAndAfterBinaryOperators != core.TSUnknown {
				p.FormatCodeSettings.InsertSpaceBeforeAndAfterBinaryOperators = overrides.FormatCodeSettings.InsertSpaceBeforeAndAfterBinaryOperators
			}
		}},
		{rawName: "insertSpaceAfterConstructor", configPath: "format.insertSpaceAfterConstructor", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.InsertSpaceAfterConstructor = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.InsertSpaceAfterConstructor)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.InsertSpaceAfterConstructor != core.TSUnknown {
				p.FormatCodeSettings.InsertSpaceAfterConstructor = overrides.FormatCodeSettings.InsertSpaceAfterConstructor
			}
		}},
		{rawName: "insertSpaceAfterKeywordsInControlFlowStatements", configPath: "format.insertSpaceAfterKeywordsInControlFlowStatements", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.InsertSpaceAfterKeywordsInControlFlowStatements = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.InsertSpaceAfterKeywordsInControlFlowStatements)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.InsertSpaceAfterKeywordsInControlFlowStatements != core.TSUnknown {
				p.FormatCodeSettings.InsertSpaceAfterKeywordsInControlFlowStatements = overrides.FormatCodeSettings.InsertSpaceAfterKeywordsInControlFlowStatements
			}
		}},
		{rawName: "insertSpaceAfterFunctionKeywordForAnonymousFunctions", configPath: "format.insertSpaceAfterFunctionKeywordForAnonymousFunctions", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.InsertSpaceAfterFunctionKeywordForAnonymousFunctions = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.InsertSpaceAfterFunctionKeywordForAnonymousFunctions)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.InsertSpaceAfterFunctionKeywordForAnonymousFunctions != core.TSUnknown {
				p.FormatCodeSettings.InsertSpaceAfterFunctionKeywordForAnonymousFunctions = overrides.FormatCodeSettings.InsertSpaceAfterFunctionKeywordForAnonymousFunctions
			}
		}},
		{rawName: "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis", configPath: "format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis != core.TSUnknown {
				p.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis = overrides.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis
			}
		}},
		{rawName: "insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets", configPath: "format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets != core.TSUnknown {
				p.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets = overrides.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets
			}
		}},
		{rawName: "insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces", configPath: "format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingNonemptyBraces = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingNonemptyBraces)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingNonemptyBraces != core.TSUnknown {
				p.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingNonemptyBraces = overrides.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingNonemptyBraces
			}
		}},
		{rawName: "insertSpaceAfterOpeningAndBeforeClosingEmptyBraces", configPath: "format.insertSpaceAfterOpeningAndBeforeClosingEmptyBraces", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingEmptyBraces = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingEmptyBraces)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingEmptyBraces != core.TSUnknown {
				p.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingEmptyBraces = overrides.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingEmptyBraces
			}
		}},
		{rawName: "insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces", configPath: "format.insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces != core.TSUnknown {
				p.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces = overrides.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces
			}
		}},
		{rawName: "insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces", configPath: "format.insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces != core.TSUnknown {
				p.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces = overrides.FormatCodeSettings.InsertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces
			}
		}},
		{rawName: "insertSpaceAfterTypeAssertion", configPath: "format.insertSpaceAfterTypeAssertion", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.InsertSpaceAfterTypeAssertion = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.InsertSpaceAfterTypeAssertion)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.InsertSpaceAfterTypeAssertion != core.TSUnknown {
				p.FormatCodeSettings.InsertSpaceAfterTypeAssertion = overrides.FormatCodeSettings.InsertSpaceAfterTypeAssertion
			}
		}},
		{rawName: "insertSpaceBeforeFunctionParenthesis", configPath: "format.insertSpaceBeforeFunctionParenthesis", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.InsertSpaceBeforeFunctionParenthesis = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.InsertSpaceBeforeFunctionParenthesis)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.InsertSpaceBeforeFunctionParenthesis != core.TSUnknown {
				p.FormatCodeSettings.InsertSpaceBeforeFunctionParenthesis = overrides.FormatCodeSettings.InsertSpaceBeforeFunctionParenthesis
			}
		}},
		{rawName: "placeOpenBraceOnNewLineForFunctions", configPath: "format.placeOpenBraceOnNewLineForFunctions", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.PlaceOpenBraceOnNewLineForFunctions = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.PlaceOpenBraceOnNewLineForFunctions)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.PlaceOpenBraceOnNewLineForFunctions != core.TSUnknown {
				p.FormatCodeSettings.PlaceOpenBraceOnNewLineForFunctions = overrides.FormatCodeSettings.PlaceOpenBraceOnNewLineForFunctions
			}
		}},
		{rawName: "placeOpenBraceOnNewLineForControlBlocks", configPath: "format.placeOpenBraceOnNewLineForControlBlocks", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.PlaceOpenBraceOnNewLineForControlBlocks = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.PlaceOpenBraceOnNewLineForControlBlocks)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.PlaceOpenBraceOnNewLineForControlBlocks != core.TSUnknown {
				p.FormatCodeSettings.PlaceOpenBraceOnNewLineForControlBlocks = overrides.FormatCodeSettings.PlaceOpenBraceOnNewLineForControlBlocks
			}
		}},
		{rawName: "insertSpaceBeforeTypeAnnotation", configPath: "format.insertSpaceBeforeTypeAnnotation", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.InsertSpaceBeforeTypeAnnotation = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.InsertSpaceBeforeTypeAnnotation)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.InsertSpaceBeforeTypeAnnotation != core.TSUnknown {
				p.FormatCodeSettings.InsertSpaceBeforeTypeAnnotation = overrides.FormatCodeSettings.InsertSpaceBeforeTypeAnnotation
			}
		}},
		{rawName: "indentMultiLineObjectLiteralBeginningOnBlankLine", configPath: "format.indentMultiLineObjectLiteralBeginningOnBlankLine", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.IndentMultiLineObjectLiteralBeginningOnBlankLine = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.IndentMultiLineObjectLiteralBeginningOnBlankLine)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.IndentMultiLineObjectLiteralBeginningOnBlankLine != core.TSUnknown {
				p.FormatCodeSettings.IndentMultiLineObjectLiteralBeginningOnBlankLine = overrides.FormatCodeSettings.IndentMultiLineObjectLiteralBeginningOnBlankLine
			}
		}},
		{rawName: "semicolons", configPath: "format.semicolons", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.FormatCodeSettings.Semicolons = parseSemicolonPreference(val) }, serialize: func(p *UserPreferences) any {
			return serializePreferenceString(string(p.FormatCodeSettings.Semicolons))
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if string(overrides.FormatCodeSettings.Semicolons) != "" {
				p.FormatCodeSettings.Semicolons = overrides.FormatCodeSettings.Semicolons
			}
		}},
		{rawName: "indentSwitchCase", configPath: "format.indentSwitchCase", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.FormatCodeSettings.IndentSwitchCase = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.FormatCodeSettings.IndentSwitchCase)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.FormatCodeSettings.IndentSwitchCase != core.TSUnknown {
				p.FormatCodeSettings.IndentSwitchCase = overrides.FormatCodeSettings.IndentSwitchCase
			}
		}},
		{rawName: "quotePreference", configPath: "preferences.quoteStyle", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.QuotePreference = parsePreferenceQuote(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceString(string(p.QuotePreference)) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if string(overrides.QuotePreference) != "" {
				p.QuotePreference = overrides.QuotePreference
			}
		}},
		{rawName: "lazyConfiguredProjectsFromExternalProject", configPath: "", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.LazyConfiguredProjectsFromExternalProject = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.LazyConfiguredProjectsFromExternalProject)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.LazyConfiguredProjectsFromExternalProject != core.TSUnknown {
				p.LazyConfiguredProjectsFromExternalProject = overrides.LazyConfiguredProjectsFromExternalProject
			}
		}},
		{rawName: "maximumHoverLength", configPath: "", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.MaximumHoverLength = parsePreferenceInt(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceInt(int(p.MaximumHoverLength)) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.MaximumHoverLength != 0 {
				p.MaximumHoverLength = overrides.MaximumHoverLength
			}
		}},
		{rawName: "includeCompletionsForModuleExports", configPath: "suggest.autoImports", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.IncludeCompletionsForModuleExports = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.IncludeCompletionsForModuleExports) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.IncludeCompletionsForModuleExports != core.TSUnknown {
				p.IncludeCompletionsForModuleExports = overrides.IncludeCompletionsForModuleExports
			}
		}},
		{rawName: "includeCompletionsForImportStatements", configPath: "suggest.includeCompletionsForImportStatements", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.IncludeCompletionsForImportStatements = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.IncludeCompletionsForImportStatements)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.IncludeCompletionsForImportStatements != core.TSUnknown {
				p.IncludeCompletionsForImportStatements = overrides.IncludeCompletionsForImportStatements
			}
		}},
		{rawName: "includeAutomaticOptionalChainCompletions", configPath: "suggest.includeAutomaticOptionalChainCompletions", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.IncludeAutomaticOptionalChainCompletions = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.IncludeAutomaticOptionalChainCompletions)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.IncludeAutomaticOptionalChainCompletions != core.TSUnknown {
				p.IncludeAutomaticOptionalChainCompletions = overrides.IncludeAutomaticOptionalChainCompletions
			}
		}},
		{rawName: "includeCompletionsWithClassMemberSnippets", configPath: "suggest.classMemberSnippets.enabled", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.IncludeCompletionsWithClassMemberSnippets = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.IncludeCompletionsWithClassMemberSnippets)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.IncludeCompletionsWithClassMemberSnippets != core.TSUnknown {
				p.IncludeCompletionsWithClassMemberSnippets = overrides.IncludeCompletionsWithClassMemberSnippets
			}
		}},
		{rawName: "includeCompletionsWithObjectLiteralMethodSnippets", configPath: "suggest.objectLiteralMethodSnippets.enabled", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.IncludeCompletionsWithObjectLiteralMethodSnippets = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.IncludeCompletionsWithObjectLiteralMethodSnippets)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.IncludeCompletionsWithObjectLiteralMethodSnippets != core.TSUnknown {
				p.IncludeCompletionsWithObjectLiteralMethodSnippets = overrides.IncludeCompletionsWithObjectLiteralMethodSnippets
			}
		}},
		{rawName: "jsxAttributeCompletionStyle", configPath: "preferences.jsxAttributeCompletionStyle", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.JsxAttributeCompletionStyle = parsePreferenceJSXAttributeCompletionStyle(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceJSXAttributeCompletionStyle(p.JsxAttributeCompletionStyle)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if string(overrides.JsxAttributeCompletionStyle) != "" {
				p.JsxAttributeCompletionStyle = overrides.JsxAttributeCompletionStyle
			}
		}},
		{rawName: "autoClosingTags", configPath: "autoClosingTags.enabled", fallbackConfigPaths: []configPathInfo{{path: "autoClosingTags", invert: false}}, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.EnableAutoClosingTags = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.EnableAutoClosingTags) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.EnableAutoClosingTags != core.TSUnknown {
				p.EnableAutoClosingTags = overrides.EnableAutoClosingTags
			}
		}},
		{rawName: "completeJSDocs", configPath: "suggest.jsdoc.enabled", fallbackConfigPaths: []configPathInfo{{path: "suggest.completeJSDocs", invert: false}}, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.EnableJSDocCompletions = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.EnableJSDocCompletions) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.EnableJSDocCompletions != core.TSUnknown {
				p.EnableJSDocCompletions = overrides.EnableJSDocCompletions
			}
		}},
		{rawName: "generateReturnInDocTemplate", configPath: "suggest.jsdoc.generateReturns", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.GenerateReturnInDocTemplate = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.GenerateReturnInDocTemplate) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.GenerateReturnInDocTemplate != core.TSUnknown {
				p.GenerateReturnInDocTemplate = overrides.GenerateReturnInDocTemplate
			}
		}},
		{rawName: "importModuleSpecifierPreference", configPath: "preferences.importModuleSpecifier", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.ImportModuleSpecifierPreference = parsePreferenceImportModuleSpecifier(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceImportModuleSpecifier(p.ImportModuleSpecifierPreference)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if string(overrides.ImportModuleSpecifierPreference) != "" {
				p.ImportModuleSpecifierPreference = overrides.ImportModuleSpecifierPreference
			}
		}},
		{rawName: "importModuleSpecifierEnding", configPath: "preferences.importModuleSpecifierEnding", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.ImportModuleSpecifierEnding = parsePreferenceImportModuleSpecifierEnding(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceImportModuleSpecifierEnding(p.ImportModuleSpecifierEnding)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if string(overrides.ImportModuleSpecifierEnding) != "" {
				p.ImportModuleSpecifierEnding = overrides.ImportModuleSpecifierEnding
			}
		}},
		{rawName: "autoImportSpecifierExcludeRegexes", configPath: "preferences.autoImportSpecifierExcludeRegexes", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.AutoImportSpecifierExcludeRegexes = parsePreferenceStringSlice(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceStringSlice(p.AutoImportSpecifierExcludeRegexes)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.AutoImportSpecifierExcludeRegexes != nil {
				p.AutoImportSpecifierExcludeRegexes = overrides.AutoImportSpecifierExcludeRegexes
			}
		}},
		{rawName: "autoImportFileExcludePatterns", configPath: "preferences.autoImportFileExcludePatterns", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.AutoImportFileExcludePatterns = parsePreferenceStringSlice(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceStringSlice(p.AutoImportFileExcludePatterns) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.AutoImportFileExcludePatterns != nil {
				p.AutoImportFileExcludePatterns = overrides.AutoImportFileExcludePatterns
			}
		}},
		{rawName: "autoImportEntrypointDirectorySearch", configPath: "preferences.autoImportEntrypointDirectorySearch", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.AutoImportEntrypointDirectorySearch = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.AutoImportEntrypointDirectorySearch)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.AutoImportEntrypointDirectorySearch != core.TSUnknown {
				p.AutoImportEntrypointDirectorySearch = overrides.AutoImportEntrypointDirectorySearch
			}
		}},
		{rawName: "preferTypeOnlyAutoImports", configPath: "preferences.preferTypeOnlyAutoImports", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.PreferTypeOnlyAutoImports = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.PreferTypeOnlyAutoImports) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.PreferTypeOnlyAutoImports != core.TSUnknown {
				p.PreferTypeOnlyAutoImports = overrides.PreferTypeOnlyAutoImports
			}
		}},
		{rawName: "organizeImportsSort", configPath: "preferences.organizeImports.sort", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.OrganizeImportsSort = parsePreferenceOrganizeImportsSort(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceOrganizeImportsSort(p.OrganizeImportsSort) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.OrganizeImportsSort != 0 {
				p.OrganizeImportsSort = overrides.OrganizeImportsSort
			}
		}},
		{rawName: "organizeImportsIgnoreCase", configPath: "preferences.organizeImports.caseSensitivity", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.OrganizeImportsIgnoreCase = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.OrganizeImportsIgnoreCase) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.OrganizeImportsIgnoreCase != core.TSUnknown {
				p.OrganizeImportsIgnoreCase = overrides.OrganizeImportsIgnoreCase
			}
		}},
		{rawName: "organizeImportsCollation", configPath: "preferences.organizeImports.unicodeCollation", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.OrganizeImportsCollation = parsePreferenceOrganizeImportsCollation(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceOrganizeImportsCollation(p.OrganizeImportsCollation)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if bool(overrides.OrganizeImportsCollation) {
				p.OrganizeImportsCollation = overrides.OrganizeImportsCollation
			}
		}},
		{rawName: "organizeImportsLocale", configPath: "preferences.organizeImports.locale", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.OrganizeImportsLocale = parsePreferenceString(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceString(string(p.OrganizeImportsLocale)) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if string(overrides.OrganizeImportsLocale) != "" {
				p.OrganizeImportsLocale = overrides.OrganizeImportsLocale
			}
		}},
		{rawName: "organizeImportsNumericCollation", configPath: "preferences.organizeImports.numericCollation", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.OrganizeImportsNumericCollation = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.OrganizeImportsNumericCollation) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.OrganizeImportsNumericCollation != core.TSUnknown {
				p.OrganizeImportsNumericCollation = overrides.OrganizeImportsNumericCollation
			}
		}},
		{rawName: "organizeImportsAccentCollation", configPath: "preferences.organizeImports.accentCollation", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.OrganizeImportsAccentCollation = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.OrganizeImportsAccentCollation) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.OrganizeImportsAccentCollation != core.TSUnknown {
				p.OrganizeImportsAccentCollation = overrides.OrganizeImportsAccentCollation
			}
		}},
		{rawName: "organizeImportsCaseFirst", configPath: "preferences.organizeImports.caseFirst", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.OrganizeImportsCaseFirst = parsePreferenceOrganizeImportsCaseFirst(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceOrganizeImportsCaseFirst(p.OrganizeImportsCaseFirst)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.OrganizeImportsCaseFirst != 0 {
				p.OrganizeImportsCaseFirst = overrides.OrganizeImportsCaseFirst
			}
		}},
		{rawName: "organizeImportsTypeOrder", configPath: "preferences.organizeImports.typeOrder", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.OrganizeImportsTypeOrder = parsePreferenceOrganizeImportsTypeOrder(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceOrganizeImportsTypeOrder(p.OrganizeImportsTypeOrder)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.OrganizeImportsTypeOrder != 0 {
				p.OrganizeImportsTypeOrder = overrides.OrganizeImportsTypeOrder
			}
		}},
		{rawName: "allowTextChangesInNewFiles", configPath: "", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.AllowTextChangesInNewFiles = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.AllowTextChangesInNewFiles) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.AllowTextChangesInNewFiles != core.TSUnknown {
				p.AllowTextChangesInNewFiles = overrides.AllowTextChangesInNewFiles
			}
		}},
		{rawName: "providePrefixAndSuffixTextForRename", configPath: "preferences.useAliasesForRenames", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.UseAliasesForRename = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.UseAliasesForRename) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.UseAliasesForRename != core.TSUnknown {
				p.UseAliasesForRename = overrides.UseAliasesForRename
			}
		}},
		{rawName: "allowRenameOfImportPath", configPath: "", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.AllowRenameOfImportPath = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.AllowRenameOfImportPath) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.AllowRenameOfImportPath != core.TSUnknown {
				p.AllowRenameOfImportPath = overrides.AllowRenameOfImportPath
			}
		}},
		{rawName: "provideRefactorNotApplicableReason", configPath: "", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.ProvideRefactorNotApplicableReason = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.ProvideRefactorNotApplicableReason) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.ProvideRefactorNotApplicableReason != core.TSUnknown {
				p.ProvideRefactorNotApplicableReason = overrides.ProvideRefactorNotApplicableReason
			}
		}},
		{rawName: "includeInlayParameterNameHints", configPath: "inlayHints.parameterNames.enabled", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.InlayHints.IncludeInlayParameterNameHints = parsePreferenceIncludeInlayParameterNameHints(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceString(string(p.InlayHints.IncludeInlayParameterNameHints))
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if string(overrides.InlayHints.IncludeInlayParameterNameHints) != "" {
				p.InlayHints.IncludeInlayParameterNameHints = overrides.InlayHints.IncludeInlayParameterNameHints
			}
		}},
		{rawName: "includeInlayParameterNameHintsWhenArgumentMatchesName", configPath: "inlayHints.parameterNames.suppressWhenArgumentMatchesName", fallbackConfigPaths: nil, rawInvert: false, configInvert: true, set: func(p *UserPreferences, val any) {
			p.InlayHints.IncludeInlayParameterNameHintsWhenArgumentMatchesName = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.InlayHints.IncludeInlayParameterNameHintsWhenArgumentMatchesName)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.InlayHints.IncludeInlayParameterNameHintsWhenArgumentMatchesName != core.TSUnknown {
				p.InlayHints.IncludeInlayParameterNameHintsWhenArgumentMatchesName = overrides.InlayHints.IncludeInlayParameterNameHintsWhenArgumentMatchesName
			}
		}},
		{rawName: "includeInlayFunctionParameterTypeHints", configPath: "inlayHints.parameterTypes.enabled", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.InlayHints.IncludeInlayFunctionParameterTypeHints = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.InlayHints.IncludeInlayFunctionParameterTypeHints)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.InlayHints.IncludeInlayFunctionParameterTypeHints != core.TSUnknown {
				p.InlayHints.IncludeInlayFunctionParameterTypeHints = overrides.InlayHints.IncludeInlayFunctionParameterTypeHints
			}
		}},
		{rawName: "includeInlayVariableTypeHints", configPath: "inlayHints.variableTypes.enabled", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.InlayHints.IncludeInlayVariableTypeHints = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.InlayHints.IncludeInlayVariableTypeHints)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.InlayHints.IncludeInlayVariableTypeHints != core.TSUnknown {
				p.InlayHints.IncludeInlayVariableTypeHints = overrides.InlayHints.IncludeInlayVariableTypeHints
			}
		}},
		{rawName: "includeInlayVariableTypeHintsWhenTypeMatchesName", configPath: "inlayHints.variableTypes.suppressWhenTypeMatchesName", fallbackConfigPaths: nil, rawInvert: false, configInvert: true, set: func(p *UserPreferences, val any) {
			p.InlayHints.IncludeInlayVariableTypeHintsWhenTypeMatchesName = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.InlayHints.IncludeInlayVariableTypeHintsWhenTypeMatchesName)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.InlayHints.IncludeInlayVariableTypeHintsWhenTypeMatchesName != core.TSUnknown {
				p.InlayHints.IncludeInlayVariableTypeHintsWhenTypeMatchesName = overrides.InlayHints.IncludeInlayVariableTypeHintsWhenTypeMatchesName
			}
		}},
		{rawName: "includeInlayPropertyDeclarationTypeHints", configPath: "inlayHints.propertyDeclarationTypes.enabled", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.InlayHints.IncludeInlayPropertyDeclarationTypeHints = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.InlayHints.IncludeInlayPropertyDeclarationTypeHints)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.InlayHints.IncludeInlayPropertyDeclarationTypeHints != core.TSUnknown {
				p.InlayHints.IncludeInlayPropertyDeclarationTypeHints = overrides.InlayHints.IncludeInlayPropertyDeclarationTypeHints
			}
		}},
		{rawName: "includeInlayFunctionLikeReturnTypeHints", configPath: "inlayHints.functionLikeReturnTypes.enabled", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.InlayHints.IncludeInlayFunctionLikeReturnTypeHints = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.InlayHints.IncludeInlayFunctionLikeReturnTypeHints)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.InlayHints.IncludeInlayFunctionLikeReturnTypeHints != core.TSUnknown {
				p.InlayHints.IncludeInlayFunctionLikeReturnTypeHints = overrides.InlayHints.IncludeInlayFunctionLikeReturnTypeHints
			}
		}},
		{rawName: "includeInlayEnumMemberValueHints", configPath: "inlayHints.enumMemberValues.enabled", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.InlayHints.IncludeInlayEnumMemberValueHints = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.InlayHints.IncludeInlayEnumMemberValueHints)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.InlayHints.IncludeInlayEnumMemberValueHints != core.TSUnknown {
				p.InlayHints.IncludeInlayEnumMemberValueHints = overrides.InlayHints.IncludeInlayEnumMemberValueHints
			}
		}},
		{rawName: "referencesCodeLensEnabled", configPath: "referencesCodeLens.enabled", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.CodeLens.ReferencesCodeLensEnabled = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.CodeLens.ReferencesCodeLensEnabled) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.CodeLens.ReferencesCodeLensEnabled != core.TSUnknown {
				p.CodeLens.ReferencesCodeLensEnabled = overrides.CodeLens.ReferencesCodeLensEnabled
			}
		}},
		{rawName: "implementationsCodeLensEnabled", configPath: "implementationsCodeLens.enabled", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.CodeLens.ImplementationsCodeLensEnabled = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.CodeLens.ImplementationsCodeLensEnabled)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.CodeLens.ImplementationsCodeLensEnabled != core.TSUnknown {
				p.CodeLens.ImplementationsCodeLensEnabled = overrides.CodeLens.ImplementationsCodeLensEnabled
			}
		}},
		{rawName: "referencesCodeLensShowOnAllFunctions", configPath: "referencesCodeLens.showOnAllFunctions", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.CodeLens.ReferencesCodeLensShowOnAllFunctions = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.CodeLens.ReferencesCodeLensShowOnAllFunctions)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.CodeLens.ReferencesCodeLensShowOnAllFunctions != core.TSUnknown {
				p.CodeLens.ReferencesCodeLensShowOnAllFunctions = overrides.CodeLens.ReferencesCodeLensShowOnAllFunctions
			}
		}},
		{rawName: "implementationsCodeLensShowOnInterfaceMethods", configPath: "implementationsCodeLens.showOnInterfaceMethods", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.CodeLens.ImplementationsCodeLensShowOnInterfaceMethods = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.CodeLens.ImplementationsCodeLensShowOnInterfaceMethods)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.CodeLens.ImplementationsCodeLensShowOnInterfaceMethods != core.TSUnknown {
				p.CodeLens.ImplementationsCodeLensShowOnInterfaceMethods = overrides.CodeLens.ImplementationsCodeLensShowOnInterfaceMethods
			}
		}},
		{rawName: "implementationsCodeLensShowOnAllClassMethods", configPath: "implementationsCodeLens.showOnAllClassMethods", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.CodeLens.ImplementationsCodeLensShowOnAllClassMethods = parsePreferenceTristate(val)
		}, serialize: func(p *UserPreferences) any {
			return serializePreferenceTristate(p.CodeLens.ImplementationsCodeLensShowOnAllClassMethods)
		}, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.CodeLens.ImplementationsCodeLensShowOnAllClassMethods != core.TSUnknown {
				p.CodeLens.ImplementationsCodeLensShowOnAllClassMethods = overrides.CodeLens.ImplementationsCodeLensShowOnAllClassMethods
			}
		}},
		{rawName: "preferGoToSourceDefinition", configPath: "", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.PreferGoToSourceDefinition = parsePreferenceBool(val) }, serialize: func(p *UserPreferences) any { return p.PreferGoToSourceDefinition }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if bool(overrides.PreferGoToSourceDefinition) {
				p.PreferGoToSourceDefinition = overrides.PreferGoToSourceDefinition
			}
		}},
		{rawName: "excludeLibrarySymbolsInNavTo", configPath: "workspaceSymbols.excludeLibrarySymbols", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.ExcludeLibrarySymbolsInNavTo = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.ExcludeLibrarySymbolsInNavTo) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.ExcludeLibrarySymbolsInNavTo != core.TSUnknown {
				p.ExcludeLibrarySymbolsInNavTo = overrides.ExcludeLibrarySymbolsInNavTo
			}
		}},
		{rawName: "", configPath: "workspaceSymbols.scope", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) {
			p.WorkspaceSymbolsScope = WorkspaceSymbolsScope(parsePreferenceString(val))
		}, serialize: func(p *UserPreferences) any { return serializePreferenceString(string(p.WorkspaceSymbolsScope)) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if string(overrides.WorkspaceSymbolsScope) != "" {
				p.WorkspaceSymbolsScope = overrides.WorkspaceSymbolsScope
			}
		}},
		{rawName: "formatEnabled", configPath: "format.enabled", fallbackConfigPaths: []configPathInfo{{path: "format.enable", invert: false}}, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.EnableFormatting = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.EnableFormatting) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.EnableFormatting != core.TSUnknown {
				p.EnableFormatting = overrides.EnableFormatting
			}
		}},
		{rawName: "validateEnabled", configPath: "validate.enabled", fallbackConfigPaths: []configPathInfo{{path: "validate.enable", invert: false}}, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.EnableValidation = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.EnableValidation) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.EnableValidation != core.TSUnknown {
				p.EnableValidation = overrides.EnableValidation
			}
		}},
		{rawName: "disableSuggestions", configPath: "", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.DisableSuggestions = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.DisableSuggestions) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.DisableSuggestions != core.TSUnknown {
				p.DisableSuggestions = overrides.DisableSuggestions
			}
		}},
		{rawName: "disableLineTextInReferences", configPath: "", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.DisableLineTextInReferences = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.DisableLineTextInReferences) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.DisableLineTextInReferences != core.TSUnknown {
				p.DisableLineTextInReferences = overrides.DisableLineTextInReferences
			}
		}},
		{rawName: "displayPartsForJSDoc", configPath: "", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.DisplayPartsForJSDoc = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.DisplayPartsForJSDoc) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.DisplayPartsForJSDoc != core.TSUnknown {
				p.DisplayPartsForJSDoc = overrides.DisplayPartsForJSDoc
			}
		}},
		{rawName: "reportStyleChecksAsWarnings", configPath: "reportStyleChecksAsWarnings", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.ReportStyleChecksAsWarnings = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.ReportStyleChecksAsWarnings) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.ReportStyleChecksAsWarnings != core.TSUnknown {
				p.ReportStyleChecksAsWarnings = overrides.ReportStyleChecksAsWarnings
			}
		}},
		{rawName: "", configPath: "locale", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.Locale = parsePreferenceString(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceString(string(p.Locale)) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if string(overrides.Locale) != "" {
				p.Locale = overrides.Locale
			}
		}},
		{rawName: "disableAutomaticTypeAcquisition", configPath: "disableAutomaticTypeAcquisition", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.DisableAutomaticTypeAcquisition = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.DisableAutomaticTypeAcquisition) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.DisableAutomaticTypeAcquisition != core.TSUnknown {
				p.DisableAutomaticTypeAcquisition = overrides.DisableAutomaticTypeAcquisition
			}
		}},
		{rawName: "automaticTypeAcquisitionEnabled", configPath: "tsserver.automaticTypeAcquisition.enabled", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.AutomaticTypeAcquisitionEnabled = parsePreferenceTristate(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceTristate(p.AutomaticTypeAcquisitionEnabled) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if overrides.AutomaticTypeAcquisitionEnabled != core.TSUnknown {
				p.AutomaticTypeAcquisitionEnabled = overrides.AutomaticTypeAcquisitionEnabled
			}
		}},
		{rawName: "customConfigFileName", configPath: "customConfigFileName", fallbackConfigPaths: nil, rawInvert: false, configInvert: false, set: func(p *UserPreferences, val any) { p.CustomConfigFileName = parsePreferenceString(val) }, serialize: func(p *UserPreferences) any { return serializePreferenceString(string(p.CustomConfigFileName)) }, merge: func(p *UserPreferences, overrides UserPreferences) {
			if string(overrides.CustomConfigFileName) != "" {
				p.CustomConfigFileName = overrides.CustomConfigFileName
			}
		}},
	}
}

func parsePreferenceTristate(val any) core.Tristate {
	switch val := val.(type) {
	case core.Tristate:
		return val
	case bool:
		if val {
			return core.TSTrue
		}
		return core.TSFalse
	default:
		return core.TSUnknown
	}
}

func serializePreferenceTristate(val core.Tristate) any {
	switch val {
	case core.TSTrue:
		return true
	case core.TSFalse:
		return false
	default:
		return nil
	}
}

func parsePreferenceInt(val any) int {
	switch v := val.(type) {
	case int:
		return v
	case float64:
		return int(v)
	default:
		return 0
	}
}

func serializePreferenceInt(val int) any {
	if val == 0 {
		return nil
	}
	return val
}

func parsePreferenceString(val any) string {
	if s, ok := val.(string); ok {
		return s
	}
	return ""
}

func serializePreferenceString(val string) any {
	if val == "" {
		return nil
	}
	return val
}

func parsePreferenceBool(val any) bool {
	if b, ok := val.(bool); ok {
		return b
	}
	return false
}

func parsePreferenceStringSlice(val any) []string {
	switch arr := val.(type) {
	case []string:
		return arr
	case []any:
		result := make([]string, 0, len(arr))
		for _, item := range arr {
			if s, ok := item.(string); ok {
				result = append(result, s)
			}
		}
		return result
	default:
		return nil
	}
}

func serializePreferenceStringSlice(val []string) any {
	if val == nil {
		return nil
	}
	return val
}

func parsePreferenceQuote(val any) QuotePreference {
	if s, ok := val.(string); ok {
		switch strings.ToLower(s) {
		case "auto":
			return QuotePreferenceAuto
		case "double":
			return QuotePreferenceDouble
		case "single":
			return QuotePreferenceSingle
		}
	}
	return QuotePreferenceUnknown
}

func parsePreferenceJSXAttributeCompletionStyle(val any) JsxAttributeCompletionStyle {
	if s, ok := val.(string); ok {
		switch strings.ToLower(s) {
		case "braces":
			return JsxAttributeCompletionStyleBraces
		case "none":
			return JsxAttributeCompletionStyleNone
		}
	}
	return JsxAttributeCompletionStyleAuto
}

func serializePreferenceJSXAttributeCompletionStyle(val JsxAttributeCompletionStyle) any {
	if val == JsxAttributeCompletionStyleUnknown {
		return nil
	}
	return string(val)
}

func parsePreferenceIncludeInlayParameterNameHints(val any) IncludeInlayParameterNameHints {
	if s, ok := val.(string); ok {
		switch s {
		case "all":
			return IncludeInlayParameterNameHintsAll
		case "literals":
			return IncludeInlayParameterNameHintsLiterals
		}
	}
	return IncludeInlayParameterNameHintsNone
}

func parsePreferenceOrganizeImportsSort(val any) OrganizeImportsSort {
	if s, ok := val.(string); ok {
		switch strings.ToLower(s) {
		case "ordinal":
			return OrganizeImportsSortOrdinal
		case "ordinalignorecase":
			return OrganizeImportsSortOrdinalIgnoreCase
		case "natural":
			return OrganizeImportsSortNatural
		case "naturalignorecase":
			return OrganizeImportsSortNaturalIgnoreCase
		}
	}
	return OrganizeImportsSortAuto
}

func serializePreferenceOrganizeImportsSort(val OrganizeImportsSort) any {
	switch val {
	case OrganizeImportsSortOrdinal:
		return "ordinal"
	case OrganizeImportsSortOrdinalIgnoreCase:
		return "ordinalIgnoreCase"
	case OrganizeImportsSortNatural:
		return "natural"
	case OrganizeImportsSortNaturalIgnoreCase:
		return "naturalIgnoreCase"
	default:
		return "auto"
	}
}

func parsePreferenceOrganizeImportsCollation(val any) OrganizeImportsCollation {
	if s, ok := val.(string); ok && strings.ToLower(s) == "unicode" {
		return OrganizeImportsCollationUnicode
	}
	return OrganizeImportsCollationOrdinal
}

func serializePreferenceOrganizeImportsCollation(val OrganizeImportsCollation) any {
	if val == OrganizeImportsCollationUnicode {
		return "unicode"
	}
	return "ordinal"
}

func parsePreferenceOrganizeImportsCaseFirst(val any) OrganizeImportsCaseFirst {
	if s, ok := val.(string); ok {
		switch s {
		case "lower":
			return OrganizeImportsCaseFirstLower
		case "upper":
			return OrganizeImportsCaseFirstUpper
		}
	}
	return OrganizeImportsCaseFirstFalse
}

func serializePreferenceOrganizeImportsCaseFirst(val OrganizeImportsCaseFirst) any {
	switch val {
	case OrganizeImportsCaseFirstLower:
		return "lower"
	case OrganizeImportsCaseFirstUpper:
		return "upper"
	default:
		return "default"
	}
}

func parsePreferenceOrganizeImportsTypeOrder(val any) OrganizeImportsTypeOrder {
	if s, ok := val.(string); ok {
		switch s {
		case "last":
			return OrganizeImportsTypeOrderLast
		case "inline":
			return OrganizeImportsTypeOrderInline
		case "first":
			return OrganizeImportsTypeOrderFirst
		}
	}
	return OrganizeImportsTypeOrderAuto
}

func serializePreferenceOrganizeImportsTypeOrder(val OrganizeImportsTypeOrder) any {
	switch val {
	case OrganizeImportsTypeOrderLast:
		return "last"
	case OrganizeImportsTypeOrderInline:
		return "inline"
	case OrganizeImportsTypeOrderFirst:
		return "first"
	default:
		return "auto"
	}
}

func parsePreferenceImportModuleSpecifier(val any) modulespecifiers.ImportModuleSpecifierPreference {
	if s, ok := val.(string); ok {
		switch strings.ToLower(s) {
		case "project-relative":
			return modulespecifiers.ImportModuleSpecifierPreferenceProjectRelative
		case "relative":
			return modulespecifiers.ImportModuleSpecifierPreferenceRelative
		case "non-relative":
			return modulespecifiers.ImportModuleSpecifierPreferenceNonRelative
		}
	}
	return modulespecifiers.ImportModuleSpecifierPreferenceShortest
}

func serializePreferenceImportModuleSpecifier(val modulespecifiers.ImportModuleSpecifierPreference) any {
	if val == "" {
		return nil
	}
	return string(val)
}

func parsePreferenceImportModuleSpecifierEnding(val any) modulespecifiers.ImportModuleSpecifierEndingPreference {
	if s, ok := val.(string); ok {
		switch strings.ToLower(s) {
		case "minimal":
			return modulespecifiers.ImportModuleSpecifierEndingPreferenceMinimal
		case "index":
			return modulespecifiers.ImportModuleSpecifierEndingPreferenceIndex
		case "js":
			return modulespecifiers.ImportModuleSpecifierEndingPreferenceJs
		}
	}
	return modulespecifiers.ImportModuleSpecifierEndingPreferenceAuto
}

func serializePreferenceImportModuleSpecifierEnding(val modulespecifiers.ImportModuleSpecifierEndingPreference) any {
	if val == "" {
		return nil
	}
	return string(val)
}
