package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"unicode"
	"unicode/utf8"
)

type structField struct {
	Name     string
	Type     string
	RawTag   tagInfo
	Config   tagInfo
	Fallback []tagInfo
	Exported bool
}

type tagInfo struct {
	Name   string
	Invert bool
}

type preferenceField struct {
	Accessor string
	Type     string
	Raw      tagInfo
	Config   tagInfo
	Fallback []tagInfo
}

func main() {
	repoRoot, err := findRepoRoot()
	if err != nil {
		panic(err)
	}
	structs := mustPreferenceStructs(repoRoot)
	writeFormatted(filepath.Join(repoRoot, "internal/ls/lsutil/userpreferences_generated.go"), generateUserPreferences(structs))
}

func findRepoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(wd, "go.mod")); err == nil {
			return wd, nil
		}
		next := filepath.Dir(wd)
		if next == wd {
			return "", fmt.Errorf("could not find repo root")
		}
		wd = next
	}
}

func writeFormatted(path string, src string) {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		fmt.Fprintf(os.Stderr, "%s\n", src)
		panic(err)
	}
	if err := os.WriteFile(path, formatted, 0o666); err != nil {
		panic(err)
	}
}

func mustPreferenceStructs(repoRoot string) map[string][]structField {
	result := map[string][]structField{}
	for _, relPath := range []string{
		"internal/ls/lsutil/userpreferences.go",
		"internal/ls/lsutil/formatcodeoptions.go",
	} {
		file := mustParseFile(filepath.Join(repoRoot, relPath))
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				typeSpec := spec.(*ast.TypeSpec)
				if st, ok := typeSpec.Type.(*ast.StructType); ok {
					result[typeSpec.Name.Name] = fieldsFromStruct(st)
				}
			}
		}
	}
	return result
}

func mustParseFile(path string) *ast.File {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		panic(err)
	}
	return file
}

func fieldsFromStruct(st *ast.StructType) []structField {
	var fields []structField
	for _, field := range st.Fields.List {
		fieldType := exprString(field.Type)
		tag := ""
		if field.Tag != nil {
			tag = strings.Trim(field.Tag.Value, "`")
		}
		raw := parseTagInfo(tagValue(tag, "raw"))
		config := parseTagInfo(tagValue(tag, "config"))
		var fallback []tagInfo
		for tag := range strings.SplitSeq(tagValue(tag, "fallbackConfig"), ";") {
			if tag != "" {
				fallback = append(fallback, parseTagInfo(tag))
			}
		}
		if len(field.Names) == 0 {
			name := strings.TrimPrefix(fieldType, "*")
			fields = append(fields, structField{Name: name, Type: fieldType, RawTag: raw, Config: config, Fallback: fallback, Exported: isExported(name)})
			continue
		}
		for _, name := range field.Names {
			fields = append(fields, structField{Name: name.Name, Type: fieldType, RawTag: raw, Config: config, Fallback: fallback, Exported: isExported(name.Name)})
		}
	}
	return fields
}

func exprString(expr ast.Expr) string {
	var buf bytes.Buffer
	if err := printer.Fprint(&buf, token.NewFileSet(), expr); err != nil {
		panic(err)
	}
	return buf.String()
}

func tagValue(tag, key string) string {
	prefix := key + `:"`
	start := strings.Index(tag, prefix)
	if start == -1 {
		return ""
	}
	valueStart := start + len(prefix)
	valueEnd := strings.IndexByte(tag[valueStart:], '"')
	if valueEnd == -1 {
		return ""
	}
	return tag[valueStart : valueStart+valueEnd]
}

func parseTagInfo(tag string) tagInfo {
	if tag == "" {
		return tagInfo{}
	}
	parts := strings.Split(tag, ",")
	return tagInfo{
		Name:   parts[0],
		Invert: slices.Contains(parts[1:], "invert"),
	}
}

func isExported(name string) bool {
	if name == "" || name == "_" {
		return false
	}
	r, _ := utf8.DecodeRuneInString(name)
	return unicode.IsUpper(r)
}

func generateUserPreferences(structs map[string][]structField) string {
	fields := collectPreferenceFields(structs, "UserPreferences", "p")
	var b strings.Builder
	b.WriteString("// Code generated by internal/_generate/userpreferences; DO NOT EDIT.\n\n")
	b.WriteString("package lsutil\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"strings\"\n\n")
	b.WriteString("\t\"github.com/microsoft/TypeScript/tsc/internal/core\"\n")
	b.WriteString("\t\"github.com/microsoft/TypeScript/tsc/internal/modulespecifiers\"\n")
	b.WriteString(")\n\n")

	b.WriteString("func generatedUserPreferenceFieldInfos() []fieldInfo {\n")
	b.WriteString("\treturn []fieldInfo{\n")
	for _, field := range fields {
		accessor := strings.TrimPrefix(field.Accessor, "p.")
		fmt.Fprintf(&b, "\t\t{rawName: %q, configPath: %q, fallbackConfigPaths: %s, rawInvert: %t, configInvert: %t, set: func(p *UserPreferences, val any) { p.%s = %s }, serialize: func(p *UserPreferences) any { return %s }, merge: func(p *UserPreferences, overrides UserPreferences) { if %s { p.%s = overrides.%s } }},\n",
			field.Raw.Name,
			field.Config.Name,
			configPathInfosExpr(field.Fallback),
			field.Raw.Invert,
			field.Config.Invert,
			accessor,
			parsePreferenceExpr(field.Type, "val"),
			serializePreferenceExpr(field.Type, "p."+accessor),
			nonZeroPreferenceExpr(field.Type, "overrides."+accessor),
			accessor,
			accessor,
		)
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
	b.WriteString(userPreferenceHelpers)
	return b.String()
}

func collectPreferenceFields(structs map[string][]structField, structName string, receiver string) []preferenceField {
	var result []preferenceField
	var visit func(name string, accessor string)
	visit = func(name string, accessor string) {
		for _, field := range structs[name] {
			fieldAccessor := accessor + "." + field.Name
			if field.RawTag.Name == "" && field.Config.Name == "" {
				if _, ok := structs[field.Type]; ok {
					visit(field.Type, fieldAccessor)
				}
				continue
			}
			result = append(result, preferenceField{
				Accessor: fieldAccessor,
				Type:     field.Type,
				Raw:      field.RawTag,
				Config:   field.Config,
				Fallback: field.Fallback,
			})
		}
	}
	visit(structName, receiver)
	return result
}

func configPathInfosExpr(infos []tagInfo) string {
	if len(infos) == 0 {
		return "nil"
	}
	var b strings.Builder
	b.WriteString("[]configPathInfo{")
	for _, info := range infos {
		fmt.Fprintf(&b, "{path: %q, invert: %t},", info.Name, info.Invert)
	}
	b.WriteString("}")
	return b.String()
}

func parsePreferenceExpr(fieldType string, value string) string {
	switch fieldType {
	case "core.Tristate":
		return "parsePreferenceTristate(" + value + ")"
	case "int":
		return "parsePreferenceInt(" + value + ")"
	case "string":
		return "parsePreferenceString(" + value + ")"
	case "bool":
		return "parsePreferenceBool(" + value + ")"
	case "[]string":
		return "parsePreferenceStringSlice(" + value + ")"
	case "IndentStyle":
		return "parseIndentStyle(" + value + ")"
	case "SemicolonPreference":
		return "parseSemicolonPreference(" + value + ")"
	case "QuotePreference":
		return "parsePreferenceQuote(" + value + ")"
	case "WorkspaceSymbolsScope":
		return "WorkspaceSymbolsScope(parsePreferenceString(" + value + "))"
	case "JsxAttributeCompletionStyle":
		return "parsePreferenceJSXAttributeCompletionStyle(" + value + ")"
	case "IncludeInlayParameterNameHints":
		return "parsePreferenceIncludeInlayParameterNameHints(" + value + ")"
	case "OrganizeImportsSort":
		return "parsePreferenceOrganizeImportsSort(" + value + ")"
	case "OrganizeImportsCollation":
		return "parsePreferenceOrganizeImportsCollation(" + value + ")"
	case "OrganizeImportsCaseFirst":
		return "parsePreferenceOrganizeImportsCaseFirst(" + value + ")"
	case "OrganizeImportsTypeOrder":
		return "parsePreferenceOrganizeImportsTypeOrder(" + value + ")"
	case "modulespecifiers.ImportModuleSpecifierPreference":
		return "parsePreferenceImportModuleSpecifier(" + value + ")"
	case "modulespecifiers.ImportModuleSpecifierEndingPreference":
		return "parsePreferenceImportModuleSpecifierEnding(" + value + ")"
	default:
		panic("unhandled preference type " + fieldType)
	}
}

func serializePreferenceExpr(fieldType string, accessor string) string {
	switch fieldType {
	case "core.Tristate":
		return "serializePreferenceTristate(" + accessor + ")"
	case "int", "IndentStyle":
		return "serializePreferenceInt(int(" + accessor + "))"
	case "string", "SemicolonPreference", "QuotePreference", "WorkspaceSymbolsScope", "IncludeInlayParameterNameHints":
		return "serializePreferenceString(string(" + accessor + "))"
	case "JsxAttributeCompletionStyle":
		return "serializePreferenceJSXAttributeCompletionStyle(" + accessor + ")"
	case "modulespecifiers.ImportModuleSpecifierPreference":
		return "serializePreferenceImportModuleSpecifier(" + accessor + ")"
	case "modulespecifiers.ImportModuleSpecifierEndingPreference":
		return "serializePreferenceImportModuleSpecifierEnding(" + accessor + ")"
	case "bool":
		return accessor
	case "[]string":
		return "serializePreferenceStringSlice(" + accessor + ")"
	case "OrganizeImportsSort":
		return "serializePreferenceOrganizeImportsSort(" + accessor + ")"
	case "OrganizeImportsCollation":
		return "serializePreferenceOrganizeImportsCollation(" + accessor + ")"
	case "OrganizeImportsCaseFirst":
		return "serializePreferenceOrganizeImportsCaseFirst(" + accessor + ")"
	case "OrganizeImportsTypeOrder":
		return "serializePreferenceOrganizeImportsTypeOrder(" + accessor + ")"
	default:
		panic("unhandled preference type " + fieldType)
	}
}

func nonZeroPreferenceExpr(fieldType string, accessor string) string {
	switch fieldType {
	case "core.Tristate":
		return accessor + " != core.TSUnknown"
	case "int", "IndentStyle", "OrganizeImportsSort", "OrganizeImportsCaseFirst", "OrganizeImportsTypeOrder":
		return accessor + " != 0"
	case "OrganizeImportsCollation", "bool":
		return "bool(" + accessor + ")"
	case "string", "SemicolonPreference", "QuotePreference", "WorkspaceSymbolsScope", "JsxAttributeCompletionStyle", "IncludeInlayParameterNameHints", "modulespecifiers.ImportModuleSpecifierPreference", "modulespecifiers.ImportModuleSpecifierEndingPreference":
		return `string(` + accessor + `) != ""`
	case "[]string":
		return accessor + " != nil"
	default:
		panic("unhandled preference type " + fieldType)
	}
}

const userPreferenceHelpers = `
func parsePreferenceTristate(val any) core.Tristate {
	switch val := val.(type) {
	case core.Tristate:
		return val
	case bool:
		if val {
			return core.TSTrue
		}
		return core.TSFalse
	default:
		return core.TSUnknown
	}
}

func serializePreferenceTristate(val core.Tristate) any {
	switch val {
	case core.TSTrue:
		return true
	case core.TSFalse:
		return false
	default:
		return nil
	}
}

func parsePreferenceInt(val any) int {
	switch v := val.(type) {
	case int:
		return v
	case float64:
		return int(v)
	default:
		return 0
	}
}

func serializePreferenceInt(val int) any {
	if val == 0 {
		return nil
	}
	return val
}

func parsePreferenceString(val any) string {
	if s, ok := val.(string); ok {
		return s
	}
	return ""
}

func serializePreferenceString(val string) any {
	if val == "" {
		return nil
	}
	return val
}

func parsePreferenceBool(val any) bool {
	if b, ok := val.(bool); ok {
		return b
	}
	return false
}

func parsePreferenceStringSlice(val any) []string {
	switch arr := val.(type) {
	case []string:
		return arr
	case []any:
		result := make([]string, 0, len(arr))
		for _, item := range arr {
			if s, ok := item.(string); ok {
				result = append(result, s)
			}
		}
		return result
	default:
		return nil
	}
}

func serializePreferenceStringSlice(val []string) any {
	if val == nil {
		return nil
	}
	return val
}

func parsePreferenceQuote(val any) QuotePreference {
	if s, ok := val.(string); ok {
		switch strings.ToLower(s) {
		case "auto":
			return QuotePreferenceAuto
		case "double":
			return QuotePreferenceDouble
		case "single":
			return QuotePreferenceSingle
		}
	}
	return QuotePreferenceUnknown
}

func parsePreferenceJSXAttributeCompletionStyle(val any) JsxAttributeCompletionStyle {
	if s, ok := val.(string); ok {
		switch strings.ToLower(s) {
		case "braces":
			return JsxAttributeCompletionStyleBraces
		case "none":
			return JsxAttributeCompletionStyleNone
		}
	}
	return JsxAttributeCompletionStyleAuto
}

func serializePreferenceJSXAttributeCompletionStyle(val JsxAttributeCompletionStyle) any {
	if val == JsxAttributeCompletionStyleUnknown {
		return nil
	}
	return string(val)
}

func parsePreferenceIncludeInlayParameterNameHints(val any) IncludeInlayParameterNameHints {
	if s, ok := val.(string); ok {
		switch s {
		case "all":
			return IncludeInlayParameterNameHintsAll
		case "literals":
			return IncludeInlayParameterNameHintsLiterals
		}
	}
	return IncludeInlayParameterNameHintsNone
}

func parsePreferenceOrganizeImportsSort(val any) OrganizeImportsSort {
	if s, ok := val.(string); ok {
		switch strings.ToLower(s) {
		case "ordinal":
			return OrganizeImportsSortOrdinal
		case "ordinalignorecase":
			return OrganizeImportsSortOrdinalIgnoreCase
		case "natural":
			return OrganizeImportsSortNatural
		case "naturalignorecase":
			return OrganizeImportsSortNaturalIgnoreCase
		}
	}
	return OrganizeImportsSortAuto
}

func serializePreferenceOrganizeImportsSort(val OrganizeImportsSort) any {
	switch val {
	case OrganizeImportsSortOrdinal:
		return "ordinal"
	case OrganizeImportsSortOrdinalIgnoreCase:
		return "ordinalIgnoreCase"
	case OrganizeImportsSortNatural:
		return "natural"
	case OrganizeImportsSortNaturalIgnoreCase:
		return "naturalIgnoreCase"
	default:
		return "auto"
	}
}

func parsePreferenceOrganizeImportsCollation(val any) OrganizeImportsCollation {
	if s, ok := val.(string); ok && strings.ToLower(s) == "unicode" {
		return OrganizeImportsCollationUnicode
	}
	return OrganizeImportsCollationOrdinal
}

func serializePreferenceOrganizeImportsCollation(val OrganizeImportsCollation) any {
	if val == OrganizeImportsCollationUnicode {
		return "unicode"
	}
	return "ordinal"
}

func parsePreferenceOrganizeImportsCaseFirst(val any) OrganizeImportsCaseFirst {
	if s, ok := val.(string); ok {
		switch s {
		case "lower":
			return OrganizeImportsCaseFirstLower
		case "upper":
			return OrganizeImportsCaseFirstUpper
		}
	}
	return OrganizeImportsCaseFirstFalse
}

func serializePreferenceOrganizeImportsCaseFirst(val OrganizeImportsCaseFirst) any {
	switch val {
	case OrganizeImportsCaseFirstLower:
		return "lower"
	case OrganizeImportsCaseFirstUpper:
		return "upper"
	default:
		return "default"
	}
}

func parsePreferenceOrganizeImportsTypeOrder(val any) OrganizeImportsTypeOrder {
	if s, ok := val.(string); ok {
		switch s {
		case "last":
			return OrganizeImportsTypeOrderLast
		case "inline":
			return OrganizeImportsTypeOrderInline
		case "first":
			return OrganizeImportsTypeOrderFirst
		}
	}
	return OrganizeImportsTypeOrderAuto
}

func serializePreferenceOrganizeImportsTypeOrder(val OrganizeImportsTypeOrder) any {
	switch val {
	case OrganizeImportsTypeOrderLast:
		return "last"
	case OrganizeImportsTypeOrderInline:
		return "inline"
	case OrganizeImportsTypeOrderFirst:
		return "first"
	default:
		return "auto"
	}
}

func parsePreferenceImportModuleSpecifier(val any) modulespecifiers.ImportModuleSpecifierPreference {
	if s, ok := val.(string); ok {
		switch strings.ToLower(s) {
		case "project-relative":
			return modulespecifiers.ImportModuleSpecifierPreferenceProjectRelative
		case "relative":
			return modulespecifiers.ImportModuleSpecifierPreferenceRelative
		case "non-relative":
			return modulespecifiers.ImportModuleSpecifierPreferenceNonRelative
		}
	}
	return modulespecifiers.ImportModuleSpecifierPreferenceShortest
}

func serializePreferenceImportModuleSpecifier(val modulespecifiers.ImportModuleSpecifierPreference) any {
	if val == "" {
		return nil
	}
	return string(val)
}

func parsePreferenceImportModuleSpecifierEnding(val any) modulespecifiers.ImportModuleSpecifierEndingPreference {
	if s, ok := val.(string); ok {
		switch strings.ToLower(s) {
		case "minimal":
			return modulespecifiers.ImportModuleSpecifierEndingPreferenceMinimal
		case "index":
			return modulespecifiers.ImportModuleSpecifierEndingPreferenceIndex
		case "js":
			return modulespecifiers.ImportModuleSpecifierEndingPreferenceJs
		}
	}
	return modulespecifiers.ImportModuleSpecifierEndingPreferenceAuto
}

func serializePreferenceImportModuleSpecifierEnding(val modulespecifiers.ImportModuleSpecifierEndingPreference) any {
	if val == "" {
		return nil
	}
	return string(val)
}
`
