package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"unicode"
	"unicode/utf8"
)

type structField struct {
	Name     string
	Type     string
	JSONName string
	Exported bool
}

func main() {
	repoRoot, err := findRepoRoot()
	if err != nil {
		panic(err)
	}

	fields := mustStructFields(repoRoot, "internal/core/compileroptions.go", "CompilerOptions")
	writeFormatted(filepath.Join(repoRoot, "internal/core/compileroptions_generated.go"), generateCore(fields))
	writeFormatted(filepath.Join(repoRoot, "internal/tsoptions/compileroptions_generated.go"), generateTSOptions(fields))
}

func findRepoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(wd, "go.mod")); err == nil {
			return wd, nil
		}
		next := filepath.Dir(wd)
		if next == wd {
			return "", fmt.Errorf("could not find repo root")
		}
		wd = next
	}
}

func writeFormatted(path string, src string) {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		fmt.Fprintf(os.Stderr, "%s\n", src)
		panic(err)
	}
	if err := os.WriteFile(path, formatted, 0o666); err != nil {
		panic(err)
	}
}

func mustStructFields(repoRoot, relPath, structName string) []structField {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filepath.Join(repoRoot, relPath), nil, parser.ParseComments)
	if err != nil {
		panic(err)
	}
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			typeSpec := spec.(*ast.TypeSpec)
			if typeSpec.Name.Name != structName {
				continue
			}
			st, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				panic(structName + " is not a struct")
			}
			return fieldsFromStruct(st)
		}
	}
	panic("no struct found: " + structName)
}

func fieldsFromStruct(st *ast.StructType) []structField {
	var fields []structField
	for _, field := range st.Fields.List {
		fieldType := exprString(field.Type)
		tag := ""
		if field.Tag != nil {
			tag = strings.Trim(field.Tag.Value, "`")
		}
		jsonName := tagValue(tag, "json")
		if name, _, ok := strings.Cut(jsonName, ","); ok {
			jsonName = name
		}
		if len(field.Names) == 0 {
			name := strings.TrimPrefix(fieldType, "*")
			fields = append(fields, structField{Name: name, Type: fieldType, JSONName: jsonName, Exported: isExported(name)})
			continue
		}
		for _, name := range field.Names {
			fields = append(fields, structField{Name: name.Name, Type: fieldType, JSONName: jsonName, Exported: isExported(name.Name)})
		}
	}
	return fields
}

func exprString(expr ast.Expr) string {
	var buf bytes.Buffer
	if err := printer.Fprint(&buf, token.NewFileSet(), expr); err != nil {
		panic(err)
	}
	return buf.String()
}

func tagValue(tag, key string) string {
	prefix := key + `:"`
	start := strings.Index(tag, prefix)
	if start == -1 {
		return ""
	}
	valueStart := start + len(prefix)
	valueEnd := strings.IndexByte(tag[valueStart:], '"')
	if valueEnd == -1 {
		return ""
	}
	return tag[valueStart : valueStart+valueEnd]
}

func isExported(name string) bool {
	if name == "" || name == "_" {
		return false
	}
	r, _ := utf8.DecodeRuneInString(name)
	return unicode.IsUpper(r)
}

func generateCore(fields []structField) string {
	var b strings.Builder
	b.WriteString("// Code generated by internal/_generate/compileroptions; DO NOT EDIT.\n\n")
	b.WriteString("package core\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"slices\"\n\n")
	b.WriteString("\t\"github.com/microsoft/TypeScript/tsc/internal/collections\"\n")
	b.WriteString(")\n\n")

	b.WriteString("func (options *CompilerOptions) Clone() *CompilerOptions {\n")
	b.WriteString("\ttarget := &CompilerOptions{}\n")
	for _, field := range fields {
		if field.Exported {
			fmt.Fprintf(&b, "\ttarget.%s = options.%s\n", field.Name, field.Name)
		}
	}
	b.WriteString("\treturn target\n")
	b.WriteString("}\n\n")

	b.WriteString("func (options *CompilerOptions) Equals(other *CompilerOptions) bool {\n")
	b.WriteString("\tif options == other {\n\t\treturn true\n\t}\n")
	b.WriteString("\tif options == nil || other == nil {\n\t\treturn false\n\t}\n")
	for _, field := range fields {
		if !field.Exported {
			continue
		}
		fmt.Fprintf(&b, "\tif %s {\n\t\treturn false\n\t}\n", notEqualExpr("options."+field.Name, "other."+field.Name, field.Type))
	}
	b.WriteString("\treturn true\n")
	b.WriteString("}\n\n")

	b.WriteString(coreHelpers)
	return b.String()
}

func generateTSOptions(fields []structField) string {
	var b strings.Builder
	b.WriteString("// Code generated by internal/_generate/compileroptions; DO NOT EDIT.\n\n")
	b.WriteString("package tsoptions\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"slices\"\n\n")
	b.WriteString("\t\"github.com/microsoft/TypeScript/tsc/internal/collections\"\n")
	b.WriteString("\t\"github.com/microsoft/TypeScript/tsc/internal/contentmapper\"\n")
	b.WriteString("\t\"github.com/microsoft/TypeScript/tsc/internal/core\"\n")
	b.WriteString("\t\"github.com/microsoft/TypeScript/tsc/internal/tspath\"\n")
	b.WriteString(")\n\n")

	b.WriteString("func mergeCompilerOptionsWorker(targetOptions *core.CompilerOptions, sourceOptions *core.CompilerOptions, explicitNullFields collections.Set[string]) {\n")
	for _, field := range fields {
		if !field.Exported {
			continue
		}
		jsonName := field.JSONName
		if jsonName == "" {
			jsonName = lowerFirst(field.Name)
		}
		fmt.Fprintf(&b, "\tif explicitNullFields.Has(%q) {\n\t\ttargetOptions.%s = %s\n\t} else if %s {\n\t\ttargetOptions.%s = sourceOptions.%s\n\t}\n",
			jsonName, field.Name, zeroValue(field.Type), nonZeroExpr("sourceOptions."+field.Name, field.Type), field.Name, field.Name)
	}
	b.WriteString("}\n\n")

	b.WriteString("func ForEachCompilerOptionValue(options *core.CompilerOptions, declFilter func(*CommandLineOption) bool, fn func(option *CommandLineOption, value any) bool) bool {\n")
	for _, field := range fields {
		if field.Exported {
			fmt.Fprintf(&b, "\tif optionDeclaration := CommandLineCompilerOptionsMap.Get(%q); optionDeclaration != nil && declFilter(optionDeclaration) {\n\t\tif fn(optionDeclaration, options.%s) {\n\t\t\treturn true\n\t\t}\n\t}\n", field.Name, field.Name)
		}
	}
	b.WriteString("\treturn false\n")
	b.WriteString("}\n\n")

	b.WriteString("func ForEachNonZeroCompilerOptionValue(options *core.CompilerOptions, declFilter func(*CommandLineOption) bool, fn func(option *CommandLineOption, value any) bool) bool {\n")
	for _, field := range fields {
		if field.Exported {
			fmt.Fprintf(&b, "\tif optionDeclaration := CommandLineCompilerOptionsMap.Get(%q); optionDeclaration != nil && declFilter(optionDeclaration) && %s {\n\t\tif fn(optionDeclaration, options.%s) {\n\t\t\treturn true\n\t\t}\n\t}\n", field.Name, nonZeroExpr("options."+field.Name, field.Type), field.Name)
		}
	}
	b.WriteString("\treturn false\n")
	b.WriteString("}\n\n")

	b.WriteString("func compilerOptionsHaveChanges(oldOptions *core.CompilerOptions, newOptions *core.CompilerOptions, declFilter func(*CommandLineOption) bool) bool {\n")
	b.WriteString("\tif oldOptions == newOptions {\n\t\treturn false\n\t}\n")
	b.WriteString("\tif oldOptions == nil || newOptions == nil {\n\t\treturn true\n\t}\n")
	for _, field := range fields {
		if !field.Exported {
			continue
		}
		fmt.Fprintf(&b, "\tif optionDeclaration := CommandLineCompilerOptionsMap.Get(%q); optionDeclaration != nil && declFilter(optionDeclaration) {\n", field.Name)
		b.WriteString("\t\tif optionDeclaration.strictFlag {\n")
		fmt.Fprintf(&b, "\t\t\tif compilerOptionStrictValue(oldOptions, oldOptions.%s) != compilerOptionStrictValue(newOptions, newOptions.%s) {\n\t\t\t\treturn true\n\t\t\t}\n", field.Name, field.Name)
		b.WriteString("\t\t} else if optionDeclaration.allowJsFlag {\n")
		b.WriteString("\t\t\tif oldOptions.GetAllowJS() != newOptions.GetAllowJS() {\n\t\t\t\treturn true\n\t\t\t}\n")
		fmt.Fprintf(&b, "\t\t} else if %s {\n\t\t\treturn true\n\t\t}\n", notEqualExpr("oldOptions."+field.Name, "newOptions."+field.Name, field.Type))
		b.WriteString("\t}\n")
	}
	b.WriteString("\treturn false\n")
	b.WriteString("}\n\n")

	b.WriteString("func serializeCompilerOptionsGenerated(options *core.CompilerOptions, configFilePath string, comparePathsOptions tspath.ComparePathsOptions) *collections.OrderedMap[string, any] {\n")
	b.WriteString("\tresult := collections.NewOrderedMapWithSizeHint[string, any](32)\n")
	b.WriteString("\tconfigDir := tspath.GetDirectoryPath(configFilePath)\n")
	for _, field := range fields {
		if field.Exported {
			fmt.Fprintf(&b, "\tif optionDecl := CommandLineCompilerOptionsMap.Get(%q); optionDecl != nil && shouldSerializeCompilerOption(optionDecl) && %s {\n", field.Name, nonZeroExpr("options."+field.Name, field.Type))
			fmt.Fprintf(&b, "\t\tif serialized, ok := serializeCompilerOptionValue(optionDecl, options.%s, configDir, configFilePath, comparePathsOptions); ok {\n", field.Name)
			b.WriteString("\t\t\tresult.Set(optionDecl.Name, serialized)\n\t\t}\n\t}\n")
		}
	}
	b.WriteString("\treturn result\n")
	b.WriteString("}\n\n")

	b.WriteString(tsoptionsHelpers)
	return b.String()
}

func zeroValue(fieldType string) string {
	switch fieldType {
	case "string":
		return `""`
	case "[]string", "*int", "*collections.OrderedMap[string, []string]":
		return "nil"
	default:
		return "0"
	}
}

func nonZeroExpr(accessor, fieldType string) string {
	switch fieldType {
	case "string":
		return accessor + ` != ""`
	case "[]string", "*int", "*collections.OrderedMap[string, []string]":
		return accessor + " != nil"
	default:
		return accessor + " != 0"
	}
}

func equalExpr(left, right, fieldType string) string {
	switch fieldType {
	case "[]string":
		return fmt.Sprintf("slices.Equal(%s, %s)", left, right)
	case "*int":
		return fmt.Sprintf("intPointersEqual(%s, %s)", left, right)
	case "*collections.OrderedMap[string, []string]":
		return fmt.Sprintf("compilerOptionsStringListMapEqual(%s, %s)", left, right)
	default:
		return left + " == " + right
	}
}

func notEqualExpr(left, right, fieldType string) string {
	switch fieldType {
	case "[]string":
		return fmt.Sprintf("!slices.Equal(%s, %s)", left, right)
	case "*int":
		return fmt.Sprintf("!intPointersEqual(%s, %s)", left, right)
	case "*collections.OrderedMap[string, []string]":
		return fmt.Sprintf("!compilerOptionsStringListMapEqual(%s, %s)", left, right)
	default:
		return left + " != " + right
	}
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

const coreHelpers = `
func intPointersEqual(left *int, right *int) bool {
	if left == right {
		return true
	}
	if left == nil || right == nil {
		return false
	}
	return *left == *right
}

func compilerOptionsStringListMapEqual(left *collections.OrderedMap[string, []string], right *collections.OrderedMap[string, []string]) bool {
	if left == right {
		return true
	}
	if left == nil || right == nil || left.Size() != right.Size() {
		return false
	}
	for key, leftValue := range left.Entries() {
		rightValue, ok := right.Get(key)
		if !ok || !slices.Equal(leftValue, rightValue) {
			return false
		}
	}
	return true
}

`

const tsoptionsHelpers = `
func compilerOptionsStringListMapEqual(left *collections.OrderedMap[string, []string], right *collections.OrderedMap[string, []string]) bool {
	if left == right {
		return true
	}
	if left == nil || right == nil || left.Size() != right.Size() {
		return false
	}
	for key, leftValue := range left.Entries() {
		rightValue, ok := right.Get(key)
		if !ok || !slices.Equal(leftValue, rightValue) {
			return false
		}
	}
	return true
}

func intPointersEqual(left *int, right *int) bool {
	if left == right {
		return true
	}
	if left == nil || right == nil {
		return false
	}
	return *left == *right
}

func compilerOptionStrictValue(options *core.CompilerOptions, value any) bool {
	if value, ok := value.(core.Tristate); ok {
		return options.GetStrictOptionValue(value)
	}
	return false
}

func watchOptionsEqual(left *core.WatchOptions, right *core.WatchOptions) bool {
	if left == right {
		return true
	}
	if left == nil || right == nil {
		return false
	}
	return intPointersEqual(left.Interval, right.Interval) &&
		left.FileKind == right.FileKind &&
		left.DirectoryKind == right.DirectoryKind &&
		left.FallbackPolling == right.FallbackPolling &&
		left.SyncWatchDir == right.SyncWatchDir &&
		slices.Equal(left.ExcludeDir, right.ExcludeDir) &&
		slices.Equal(left.ExcludeFiles, right.ExcludeFiles)
}

func projectReferencesEqual(left []*core.ProjectReference, right []*core.ProjectReference) bool {
	if len(left) != len(right) {
		return false
	}
	for i := range left {
		if left[i] == right[i] {
			continue
		}
		if left[i] == nil || right[i] == nil ||
			left[i].Path != right[i].Path ||
			left[i].OriginalPath != right[i].OriginalPath ||
			left[i].Circular != right[i].Circular {
			return false
		}
	}
	return true
}

func (p *ParsedOptions) Equals(other *ParsedOptions) bool {
	if p == other {
		return true
	}
	if p == nil || other == nil {
		return false
	}
	return p.CompilerOptions.Equals(other.CompilerOptions) &&
		watchOptionsEqual(p.WatchOptions, other.WatchOptions) &&
		p.TypeAcquisition.Equals(other.TypeAcquisition) &&
		slices.Equal(p.FileNames, other.FileNames) &&
		projectReferencesEqual(p.ProjectReferences, other.ProjectReferences) &&
		slices.EqualFunc(p.ContentMappers, other.ContentMappers, (*contentmapper.Mapper).Equals)
}
`
